services:
  postgres:
    image: postgres:15-alpine
    container_name: ares-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ares-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog
    container_name: ares-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  pgadmin:
    image: dpage/pgadmin4
    container_name: ares-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./docker/servers.json:/pgadmin4/servers.json
      - ./docker/pgpass:/var/lib/pgadmin/pgpass
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  backend:
    build: .
    container_name: ares-backend
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      JWT_SECRET: ${JWT_SECRET}
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - postgres
      - redis
      - mailhog

  frontend:
    build: ./frontend
    container_name: ares-frontend
    ports:
      - "4200:4000"
    environment:
      PORT: 4000
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
