spring:
    profiles:
        active: dev
    application:
        name: Ares
    session:
        store-type: redis
user:
    password:
        min_length: 8
feed:
    interval_seconds: 300 # 5 min
    query_limit: 1000