spring:
    profiles:
        active: dev
    application:
        name: Ares
    session:
        store-type: redis
user:
    password:
        min_length: 8
feed:
    interval_seconds: 300 # 5 min
    query_limit: 1000
security:
    jwt:
        secrete: ${JWT_SECRET}
        refresh_expiration_ms: 86400000 # 24 hr
        access_expiration_ms:  3600000  # 1 min