spring:
  application:
    name: Ares
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

user:
  password:
    min_length: 8
feed:
  interval_seconds: 300 # 5 min
  query_limit: 1000

security:
  jwt:
    secret: ${JWT_SECRET}
    refresh_expiration_ms: 86400000 # 24 hr
    access_expiration_ms: 3600000  # 1 hour

logging:
  file:
    name: ${spring.application.name}.log
    path: ${HOME}/Projects/logs/
  level:
    web: DEBUG
    org.springframework.security: DEBUG
