spring:
    datasource:
        driverClassName: org.apache.derby.jdbc.EmbeddedDriver
        url: jdbc:derby:memory:myDb;create=true
        username: sa
        password: password
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.community.dialect.DerbyDialect
        hibernate:
            ddl-auto: update
    security:
        user:
            password: password
security:
    jwt:
        secret: aS1hbS1hLXNlY3JldC1rZXktZm9yLWFyZXMtdGhhdC1pcy1sb25nLWVub3VnaA==
        refresh_expiration_ms: 86400000 # 24 hr
        access_expiration_ms:  3600000  # 1 min
logging:
    file:
        name: ${spring.application.name}.log
        path: ${HOME}/Projects/logs/
    level:
        web: DEBUG
        org.springframework.security: DEBUG